[project]
name = 'bassoon_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.blacklist_voters]
path = 'contracts/blacklist_voters.clar'
clarity_version = 2
epoch = 2.5

[contracts.dispute_resolution]
path = 'contracts/dispute_resolution.clar'
clarity_version = 2
epoch = 2.5

[contracts.research_fun]
path = 'contracts/research_fun.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_multi_type_support]
path = 'contracts/storage_with_multi_type_support.clar'
clarity_version = 2
epoch = 2.5

[contracts.voters_in_blacklist]
path = 'contracts/voters_in_blacklist.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
